### ISSUE TITLE
gen/db/package.json deployer files not matching root package.json settings

### ISSUE THREAD

**Issue by austinkloske22** [mikezaschka/cds-dbm#10]
I am attempting to set non-default values in the package.json migrations section to deploy to a common schema instead of public.

Each time I build using `npx cds-dbm build` the default values listed in project readme are written the the /gen/db/package.json file and therefore causing an scehma incorrect deployment.

screencast of issue:
https://www.screenpresso.com/=Annjc

**Comment by mikezaschka** [comment]
Thanks for providing this really detailed video.
The issue here is, that the [build module ](https://github.com/mikezaschka/cds-dbm/blob/main/src/build/postgres-cf/index.ts) doesn't respect the values from the root package.json, but instead uses the default values taken from the [template](https://github.com/mikezaschka/cds-dbm/blob/main/src/build/postgres-cf/template/package.json).

I will look into this on the weekend and also update to the latest versions of the other npm packages.

**Comment by mikezaschka** [comment]
Fixed in [cds-dbm@0.0.25](https://www.npmjs.com/package/cds-dbm/v/0.0.25).
