### ISSUE TITLE
Initial Release schedule?

### ISSUE THREAD

**Issue by xLexip** [mikezaschka/cds-dbm#347]
Hi there,

I'm wondering when the initial release (v1.0.0) is scheduled? With about 40 pre-releases already, some of which include some bigger adjustments in "minor releases", it can be quite challenging to manage project dependencies. While this is expected in pre-release versions, it becomes frustrating when using automations like Renovate to update dependencies. The bot tends to automatically updates packages for minor and patch releases, which can cause issues if there are significant changes. Considering the project is **"ready to be used!"** (as mentioned in the README), I believe it's about time for v1.0.0 and semantic releases.

I'd love to hear your thoughts on this matter.

**Comment by mikezaschka** [comment]
Hi @xLexip ,

this project will no longer be maintained since with version 7 of `@sap/cds` there is a native PostgreSQL integration in place that also supports the deployment of the data model via `cds deploy`.
More infos here: https://cap.cloud.sap/docs/guides/databases-postgres

So, there won't be a version 1.0.0.

Kind Regards,

Mike
